### ISSUE TITLE
Issues on BigSur with SSL certificates while using Websockets

### ISSUE THREAD

**Issue by pbranco1987** [aaugustin/websockets#1008]
Hello,

I do not have the machine details and the setup correctly in place to share with you, as my friend is having the problems, and she lives in a different country and is not in the know to document errors. 

From what I know so far, she is experiencing the same error from this thread: 
web socket isn't able to fetch data in mac. it works perfectly in my friend's laptop (ubuntu 20.04) but not in my mac (OS Big Sur). · Issue #226 · krishnavelu/alice_blue.

Also, she has seen the following error

AttributeError                            Traceback (most recent call last)
<ipython-input-4-949ee5c4821f> in <module>
     29     print('receiving messages')
     30 
---> 31 ws = websocket.WebSocketApp(SOCKET, on_open=on_open, on_close=on_close, on_message=on_message)
     32 ws.run_forever()

AttributeError: module 'websocket' has no attribute 'WebSocketApp'

while running the following code:

import time

from binance import ThreadedWebsocketManager

api_key = '<api_key'>
api_secret = '<api_secret'>

def main():

    symbol = 'BNBBTC'

    twm = ThreadedWebsocketManager(api_key=api_key, api_secret=api_secret)
    # start is required to initialise its internal loop
    twm.start()

    def handle_socket_message(msg):
        print(f"message type: {msg['e']}")
        print(msg)

    twm.start_kline_socket(callback=handle_socket_message, symbol=symbol)

    # multiple sockets can be started
    twm.start_depth_socket(callback=handle_socket_message, symbol=symbol)

    # or a multiplex socket can be started like this
    # see Binance docs for stream names
    streams = ['bnbbtc@miniTicker', 'bnbbtc@bookTicker']
    twm.start_multiplex_socket(callback=handle_socket_message, streams=streams)

    twm.join()

If more information is needed or if you have an inkling to what is happening, I am much obliged for any pointer in the right direction.

Thank you,
Paulo and Xenia

**Comment by lgrahl** [comment]
Wrong repo and also [please stop heating our planet](https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users).
